# Generated by Django 5.0.1 on 2024-03-05 08:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InteractivePosters', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('correct_answer', models.CharField(max_length=100)),
                ('machinesID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='InteractivePosters.machines')),
            ],
        ),
        migrations.DeleteModel(
            name='Test',
        ),
    ]
