# Generated by Django 5.0.1 on 2024-03-05 08:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InteractivePosters', '0002_answers_delete_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='answers',
            name='question_number',
            field=models.IntegerField(default=0, max_length=3),
        ),
    ]
