# Generated by Django 5.0.4 on 2024-05-13 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InteractivePosters', '0003_answers_question_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='machines',
            name='definition',
            field=models.CharField(default='none', max_length=385),
        ),
        migrations.AlterField(
            model_name='machines',
            name='machine_name',
            field=models.CharField(max_length=100),
        ),
    ]
