# Generated by Django 5.0.4 on 2024-05-14 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InteractivePosters', '0004_machines_definition_alter_machines_machine_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='definition',
            field=models.CharField(default='none', max_length=500),
        ),
    ]
