# Generated by Django 5.0.4 on 2024-05-15 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InteractivePosters', '0005_alter_machines_definition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='machines',
            name='machine_name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
