# Generated by Django 5.0.4 on 2024-05-21 13:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('InteractivePosters', '0008_texts_alter_answers_question_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='texts',
            old_name='text',
            new_name='definition',
        ),
    ]
