# Generated by Django 5.0.4 on 2024-05-28 11:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('InteractivePosters', '0009_rename_text_texts_definition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='texts',
            name='definition',
            field=models.CharField(max_length=1200),
        ),
    ]
